### ISSUE TITLE
Wrong setting name?

### ISSUE THREAD

**Issue by vivgui** [NickPiscitelli/Glider.js#101]
Hi Nick, 

Great work with the library! I just wanted to point out (what I think) is an issue.

See this snippet here:
https://github.com/NickPiscitelli/Glider.js/blob/56074b172e6a92e50aba7867251d96b5a66edb5e/docs/index.html#L848-L855

More specifically, this part:
```html
<code class="slim slimmer">slidesToScroll</code>
```

Shouldn't this be `slidesToShow`?

If not then you can go ahead and close this, if yes then I can go ahead and make a PR.

**Comment by NickPiscitelli** [comment]
Yup, good catch. Send a PR and I'll be happy to accept. Thanks!
