### ISSUE TITLE
different images for mobile

### ISSUE THREAD

**Issue by tarponjargon** [NickPiscitelli/Glider.js#108]
I want to show different slides for mobile browsers (ones that are created specifically for mobile browsers).  I tried the markup below which uses bootstrap classes to handle the visibility, but glider is counting every image as part of the slide set, so navigation doesn't work right.

Is the only option to instantiate two separate carousels?

`<div class="glider-contain">
    <div class="glider">
  	<div>
	    <img class="d-block d-md-none" src="/graphics/homepage/slides/slide1-mobile.jpg">
	    <img class="d-none d-md-block" src="/graphics/homepage/slides/slide1.jpg">
	</div>
  	<div>
	    <img class="d-block d-md-none" src="/graphics/homepage/slides/slide2-mobile.jpg">
	    <img class="d-none d-md-block" src="/graphics/homepage/slides/slide2.jpg">
	</div>
  	<div>
	    <img class="d-block d-md-none" src="/graphics/homepage/slides/slide3-mobile.jpg">
	    <img class="d-none d-md-block" src="/graphics/homepage/slides/slide3.jpg">
	</div>	
  </div>
</div>  `

**Comment by MykalMachon** [comment]
Hey @tarponjargon , 
I would look into using [the <picture> HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) for this! 

sounds like it should be what you're looking for.

**Comment by tarponjargon** [comment]
@MykalMachon great suggestion, thank you!
