### ISSUE TITLE
document `eventPropagate` usage

### ISSUE THREAD

**Issue by peterblazejewicz** [NickPiscitelli/Glider.js#111]
It seems the proper documentation showing intent and usage of `eventPropagate` is missing.
There is a hint of default value:
https://github.com/NickPiscitelli/Glider.js/blame/master/README.md#L90
https://github.com/NickPiscitelli/Glider.js/blob/133c568bee19028ca01a694da595a567ec8d5c8f/glider.js#L542
but no proper usage example on the docs page:
https://nickpiscitelli.github.io/Glider.js/

Thanks!

**Comment by NickPiscitelli** [comment]
The option was misnamed in the docs and has since been fixed. Thank you.

**Comment by peterblazejewicz** [comment]
@NickPiscitelli can you pint me to a commit? Someone created typescript definition for this library and this property seems to be either missing (as I can see this in the source code) or this shoudl be private (while still being in the readme: https://github.com/NickPiscitelli/Glider.js/blame/master/README.md#L90)

**Comment by martin-badin** [comment]
> It seems the proper documentation showing intent and usage of `eventPropagate` is missing.
> There is a hint of default value:
> https://github.com/NickPiscitelli/Glider.js/blame/master/README.md#L90
> https://github.com/NickPiscitelli/Glider.js/blob/133c568bee19028ca01a694da595a567ec8d5c8f/glider.js#L542
> 
> 
> but no proper usage example on the docs page:
> https://nickpiscitelli.github.io/Glider.js/
> Thanks!

Please, remove `propagateEvent` from types. I think the attribute is wrong.
