### ISSUE TITLE
Responsive breakpoints are not inclusive

### ISSUE THREAD

**Issue by constb** [NickPiscitelli/Glider.js#12]
Hi!

I stumbled at adding responsiveness to my glider instance. Couldn't understand why the breakpoints don't work as I expected. The reason appears to be that in `gliderPrototype.settingsBreakpoint` you are comparing breakpoint to `window.innerWidth` using `>` which contradicts to the way `min-width` css media queries work. I think `>=` here would make more sense…

**Comment by constb** [comment]
A small follow-up to the issue: it appears the order of breakpoints is important too! If I write [ breakpoint 767 … breakpoint 1279 … ] the last one gets ignored and I get tablet styling on PC. Which also contradicts to the way media queries work, they process all relevant styles and later ones override the ones that matched earlier. I'm not sure if this should be replicated as well, or you could just reverse-sort rules by breakpoint and keep the apply-first-matched behaviour…

**Comment by NickPiscitelli** [comment]
Yes, breakpoints must go in descending order, that is listed in the
documentation.
