### ISSUE TITLE
Using Glider-JS with angular

### ISSUE THREAD

**Issue by AdrienVictor** [NickPiscitelli/Glider.js#120]
Hey all, 

Does anyone knows a way in implementing glider-js on angular. I have tried to make it work but without any success so far. I'm not too familiar into using js file with typescript on angular so I wanted to know if anyone managed to use glider-js on it.

Any help will be more than welcome :) 

thanks!

**Comment by NickPiscitelli** [comment]
There is a similar issue going on in another issue thread which already has a potential solution to the problem at hand.

https://github.com/NickPiscitelli/Glider.js/issues/139#issuecomment-778208251
