### ISSUE TITLE
Arrows missing

### ISSUE THREAD

**Issue by abishekh07** [NickPiscitelli/Glider.js#121]
I am using glider.js on multiple sections of the website). 
The arrows appear only on the first slider(i.e. first section).
All the sliders work fine, but I want the arrows to appear on all of them.

Should I rename ".glider-prev" and ".glider-next" to something else for every different slider?
Or am I missing something here?

**Comment by aurovrata** [comment]
>Should I rename ".glider-prev" and ".glider-next" to something else for every different slider?

have you tried this on another slider to see if it fixes the problem?

**Comment by NickPiscitelli** [comment]
You should pass the elements directly.

Assuming your paging controls share a parent container with glider, something like the following should work:

```
arrows: {
    next: glider.parentNode.querySelector('.glider-next'),
    prev: glider.parentNode.querySelector('.glider-prev')
}
```

**Comment by aurovrata** [comment]
That actually makes a lot of sense!
