### ISSUE TITLE
What does this CSS related to the scrollbar do?

### ISSUE THREAD

**Issue by architchandra** [NickPiscitelli/Glider.js#124]
https://github.com/NickPiscitelli/Glider.js/blob/2330bac03bd22d9f6ea783d26af038ed5f888ddd/glider.css#L116

I understand that the following CSS (starting from the line number referenced) is hiding the scrollbar on Webkit based browsers on desktop, but I can't see any change on mobile.

```
.glider::-webkit-scrollbar {
  opacity: 0;
  height: 0;
}
```

Sorry, I just feel like I need to understand what any piece of code is doing before I include it in my project. It would be great to hear from you on this.

**Comment by NickPiscitelli** [comment]
What is the question exactly? The scrollbar is styled differently depending
upon screen size.

**Comment by architchandra** [comment]
Understood now. Thanks.

Because there was such a focus on hiding the scrollbar, I was wondering if this was also trying to perform some action to that end. Because it didn't seem like it and because I didn't see any change after adding this code, I felt it might be a good idea to clarify.

Thanks a bunch for responding. Really helpful library. :)

**Comment by NickPiscitelli** [comment]
Gotcha. Yeah, it's not necessary, more of an opinionated design choice on
how I felt scrollbars should look. You're always welcome to remove, or
override the default styling to your own preference.

Glad to hear you enjoy the library.

**Comment by gvspavankumar1996** [comment]
@architchandra @NickPiscitelli  Hi my kind of struggle is different. I am unable to show scrollbar in desktop version though I am trying it with css I am unable to do so...can you please help me to add scrollbar to desktop version.
