### ISSUE TITLE
Accessibility: Certain ARIA roles must contain particular children

### ISSUE THREAD

**Issue by ArthurAssuncao** [NickPiscitelli/Glider.js#130]
ARIA role='tablist' children must have role='tab'.
To fix:
Turn
```
<div role="tablist" class="dots glider-dots">
  <button data-index="0" aria-label="Page 1" class="glider-dot active"></button>
  <button data-index="1" aria-label="Page 2" class="glider-dot "></button>
  <button data-index="2" aria-label="Page 3" class="glider-dot "></button>
</div>
```
into
```
 <div role="tablist" class="dots glider-dots">
  <button role="tab" data-index="0" aria-label="Page 1" class="glider-dot active"></button>
  <button role="tab" data-index="1" aria-label="Page 2" class="glider-dot "></button>
  <button role="tab" data-index="2" aria-label="Page 3" class="glider-dot "></button>
</div>
```

![image](https://user-images.githubusercontent.com/2515783/96154257-fc1ca480-0ee4-11eb-8da2-0a11c897ac2f.png)

**Comment by madppiper** [comment]
I would love if this was implemented.

**Comment by NickPiscitelli** [comment]
This is straight forward enough. Happy to accept a pull request for the change or I'll look to implement shortly.

**Comment by plweil** [comment]
While applying `role="tab"` to the button elements (tablist children) might bring the code into ARIA "compliance", doing this robs the button elements of their native semantics. In short, they cease to be buttons any longer, and AT users will have no idea that they are supposed to be buttons that could be clicked to initiate an action (even with the aria-label, "page 1, page 2, etc.". I'm guessing that this is not what you want. A possible solution is to wrap the buttons in divs that have `role="tab"`.
