### ISSUE TITLE
Any way to horizontally center the "center" element?

### ISSUE THREAD

**Issue by irakliShengelia** [NickPiscitelli/Glider.js#131]
![image](https://user-images.githubusercontent.com/59525444/96919376-ba7b9300-14bc-11eb-9a86-cf23e40d55d2.png)

I'm trying to get the following look on mobile devices.

Any way to achieve this?

I tried offsetting the glider-work track by -25vw, but than the first element is never visible.

Would Appreciate any tips.

**Comment by NickPiscitelli** [comment]
What are you looking to do exactly? You can center Glider, or its elements, using standard CSS to do so.
