### ISSUE TITLE
Get current visible slide

### ISSUE THREAD

**Issue by simplenotezy** [NickPiscitelli/Glider.js#134]
It would be helpful with a method so you could get the current visible slide. I am coming from Siema.js and there we had 

    this.siema = new Siema();
    this.siema.currentSlide; // e.g. "1"

**Comment by NickPiscitelli** [comment]
There is a method on the glider object called `get CurrentSlide()`. The documentation has not been updated to include it though. 


```
  gliderPrototype.getCurrentSlide = function () {
    var _ = this
    return _.round(_.ele.scrollLeft / _.itemWidth)
  }
```
