### ISSUE TITLE
Problem in gliderPrototype.bindArrows

### ISSUE THREAD

**Issue by tarponjargon** [NickPiscitelli/Glider.js#135]
I installed TrackJS on a site where I'm using glider-js heavily.  It's showing alot of instances of this error:

`Cannot read property '_func' of null`

on Chome and this one:

`null is not an object (evaluating 'n._func')`

On safari.  Both point to this in my unminified source:

```
n.bindArrows = function() {
    var e = this;
    e.opt.arrows ? ["prev", "next"].forEach((function(t) {
        var n = e.opt.arrows[t];
        n && ("string" == typeof n && (n = document.querySelector(n)), n._func =
          n._func || e.scrollItem.bind(e, t), e.event(n, "remove", {        /////////////// <<<<--- THIS LINE
            click: n._func
          }), e.event(n, "add", {
            click: n._func
          }), e.arrows[t] = n)
      })) : Object.keys(e.arrows)
      .forEach((function(t) {
        var n = e.arrows[t];
        e.event(n, "remove", {
          click: n._func
        })
      }))
  }
```
 looks like that corresponds to line 235 in https://github.com/NickPiscitelli/Glider.js/blob/master/glider.js

Seems to have happened to around 1% of users today.  Naturally, I can't reproduce it in any browser, mobile or desktop :D  

I think it's probably in my implementation of glider-js, though I am not sure where to start since I can't reproduce the issue.  

Do you have any idea what the reason for this error might be?

**Comment by tarponjargon** [comment]
Found that if the arrow specified in the options hash is a selector string that has no corresponding DOM element, error gets thrown.  #136

**Comment by NickPiscitelli** [comment]
Thanks for the thorough analysis. #136 has been merged.
