### ISSUE TITLE
display certain slide by adding a hash to URL

### ISSUE THREAD

**Issue by andrejarh** [NickPiscitelli/Glider.js#137]
Hi,
Does Glider support linking to a specific slide. (ie: /custompage#slideID)?
I couldn't find this info in the documentation.
Thanks.

**Comment by NickPiscitelli** [comment]
No, this is something that would need to be added via Glider's methods and events.

**Comment by darith27** [comment]
spliderjs has this feature, will the hash URL be a feature in any future versions?

**Comment by andrejarh** [comment]
Adding such example to the docs would be sufficient, I think.
