### ISSUE TITLE
Check that `window` is defined

### ISSUE THREAD

**Issue by stefankp** [NickPiscitelli/Glider.js#14]
Hey @NickPiscitelli,

Could you add a check here, to make sure `window` is defined?https://github.com/NickPiscitelli/Glider.js/blob/71af3bf87bd06455215efada9bd861a6ff55335b/glider.js#L23

Some tools might not have access to `window` while building and will fail. For example, trying to build with GatsbyJS failed for me because of this. They explain it here [https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined](https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined).

**Comment by NickPiscitelli** [comment]
Hm, well that's not the only place that `window` object is used, there are
a bunch of places where it's referenced. Is it possible to define the
window as an empty object before Glider? The script requires window to
function as it operates within the browser.
