### ISSUE TITLE
smooth scroll

### ISSUE THREAD

**Issue by thewhitegrizzli** [NickPiscitelli/Glider.js#151]
I can't have the glider 'glide' smoothly even with playing with scrollLock and scrollLockDelay values. Is there a future possibility if could behave perhaps more smoothly? Or maybe I'm doing something wrong.

**Comment by NickPiscitelli** [comment]
`scrollLock` and `scrollLockDelay` have no involvement in the "smoothness"
of the scrolling.

Please refer to the documentation for the behavior of options, but I
believe you may be interested in providing your own easing algorithm
