### ISSUE TITLE
How to use two instances of the slider in the same page?

### ISSUE THREAD

**Issue by tomasts248** [NickPiscitelli/Glider.js#167]
This should be added to the docs.
Edit : also how did you do it for using multiple instances in the homepage?

**Comment by tomasts248** [comment]
Okey, no suppor/answer I'm moving on to another slider that has no issies whatsoever regarding multiple instances:
https://swiperjs.com/ and tutorial on how to run multiple instances:
https://raddy.co.uk/blog/multiple-instances-of-swiperjs-on-the-same-page-with-the-same-settings/

**Comment by NickPiscitelli** [comment]
There are no issues with running multiple issues of Glider. I suspect you are instantiating the instances incorrectly and/or providing the wrong selectors to the constructor.
