### ISSUE TITLE
Arrows retain the hover color after being clicked

### ISSUE THREAD

**Issue by sjmoll** [NickPiscitelli/Glider.js#169]
If you navigate by clicking on an arrow, it keeps the hover color until you navigate with a different element (or until you reach the last item in that direction).  This can be seen with the demos on https://nickpiscitelli.github.io/Glider.js/

The screenshot shows navigation after the right arrow was just clicked.  It is not being hovered when the screenshot was taken yet has the hover color.
![Screenshot-2021-02-17 15_54_59](https://user-images.githubusercontent.com/60985617/108266954-b98c0280-7138-11eb-8eca-632dd50779fa.png)

**Comment by NickPiscitelli** [comment]
This is intentional and due to the `focus` pseudoclass on the selector. To disable, simply remove the `.glider-next:focus` and `.glider-next:focus` selectors.

**Comment by sjmoll** [comment]
Thanks for the reply.  Doing that will turn off the color change when hovering entirely, which I don't want to do.  Is there a reason why arrows retain focus after being clicked, even when the mouse is no longer hovering?

**Comment by NickPiscitelli** [comment]
Removing that rule should not affect the hover state at all. That is
controlled by the `hover` pseudoclass.

An element retains focus until another element is focused, that is standard
browser behavior.

**Comment by sjmoll** [comment]
I see I messed up when testing it earlier.  It worked now.  Thanks!
