### ISSUE TITLE
Drag is very fast on mobile

### ISSUE THREAD

**Issue by ArnaudSantucci** [NickPiscitelli/Glider.js#170]
Hello !

I use your options for dragging :
draggable: true,
dragVelocity: 1,

It's work on desktop but on mobile, he is always super fast.

Can you help me plz ?

**Comment by NickPiscitelli** [comment]
Can you provide a video of the behavior experienced? Mobile should be using native scrolling which would be controlled by the system level scroll acceleration.

**Comment by ArnaudSantucci** [comment]
Hello,
Sry it's not possible because i don't have any answers for several days. So i use an other plugin now... sry.
