### ISSUE TITLE
How to do a Fade Effect?

### ISSUE THREAD

**Issue by ggedde** [NickPiscitelli/Glider.js#174]
First off, let me say thanks for creating this.
I have been looking for a lightweight slider with breakpoints for awhile and so far this seems like the best one.

The only thing I am missing that I need occasionally is a single slide with a Fade effect instead of sliding.
So I would like to suggest 2 options:

Either a new setting for fade:true which just fades the slide or either one or multiple slides instead of sliding.
Or maybe someone can come up with some css overrides to achieve this.
I have tried some CSS overrides (position:absolute, etc) which can work except since this uses native scrolling, the active class does not follow the slides. If there was just a way to track the active slide without using the native scrolling to track it then I think I can just use css to achieve this.

Thanks

**Comment by NickPiscitelli** [comment]
Sorry for the late reply. There would be no good way to achieve this as the active slide is fully determined via scroll positioning.
