### ISSUE TITLE
Height Perspective view demo

### ISSUE THREAD

**Issue by dijkermans** [NickPiscitelli/Glider.js#176]
Hi, this 100% height is not respected on Safari / iOS 9.3.5

.glider-persp .gradient-border {

    width: 100%;
    height: 100%;
    flex: 1;

}

![glider](https://user-images.githubusercontent.com/33194795/113870793-81a55100-97b2-11eb-8a08-ea9c270cdbf6.jpg)

**Comment by NickPiscitelli** [comment]
Thanks for the report. This seems to be fixed in latest version of Safari.
