### ISSUE TITLE
How to do more than one slider in the same page?

### ISSUE THREAD

**Issue by inactivedesigner** [NickPiscitelli/Glider.js#177]
const config = {
			type: "carousel",
			perView: 3,
			breakpoints: {
				960: {
					perView: 2
				},
				330: {
					perView: 1
				}
			}
		};

		new Glide('.glide', config).mount();

Hi
This is the Javascript markup I have used for the slider. Now if I add more than one slider in the same web page which have some different variations, like different perView, how to go about it? I could change the class in the html, followed by adding those classes in the glide.css. But I'm not so sure about the Javascript code.

**Comment by apacholik** [comment]
Hi, @inactivedesigner 
This is GLIDE**R** not GLIDE. You should search help https://github.com/glidejs/glide.

**Comment by inactivedesigner** [comment]
Yeah I figured and fixed the issue. Thanks though!
