### ISSUE TITLE
Issues when using multiple glider.js sliders on same page

### ISSUE THREAD

**Issue by ralex78** [NickPiscitelli/Glider.js#179]
Hi!

I have integrated multiple glider.js slider on the same page, for various product carousels. When using only one glider.js carousel everything works fine. As soon as I am using multiple sliders I am running into the following issue:

- Reloading the page without browser cache: all sliders work correctly
- Reloading the page with browser cache only one slider works correcly. On all other sliders Glider JS is not being applied at all.

I am using a unique ID for each carousel and have integrated a separate script tag for each slider. I am using glider.js on a Magento 2.4 project via RequireJS:

`<script>`
`require(['glider'], function ($) {`
`window.addEventListener('load', function () {`
`window.glides = new Glider(document.getElementById('glider1'), {`
`draggable: true, `
`dots: '#glide1-dots', `
`arrows: {prev: '#glide1-prev',next: '#glide1-next'},`
`responsive: [{breakpoint: 0,settings: {slidesToShow: 2,slidesToScroll: 2}},{breakpoint: 768,settings: {slidesToShow: 3,slidesToScroll: 3}}]`
`}) });`
`});`
`</script>`

Best wishes,
Alex

**Comment by dsacramone** [comment]
> Hi!
> 
> I have integrated multiple glider.js slider on the same page, for various product carousels. When using only one glider.js carousel everything works fine. As soon as I am using multiple sliders I am running into the following issue:
> 
> * Reloading the page without browser cache: all sliders work correctly
> * Reloading the page with browser cache only one slider works correcly. On all other sliders Glider JS is not being applied at all.
> 
> I am using a unique ID for each carousel and have integrated a separate script tag for each slider. I am using glider.js on a Magento 2.4 project via RequireJS:
> 
> `<script>`
> `require(['glider'], function ($) {`
> `window.addEventListener('load', function () {`
> `window.glides = new Glider(document.getElementById('glider1'), {`
> `draggable: true, `
> `dots: '#glide1-dots', `
> `arrows: {prev: '#glide1-prev',next: '#glide1-next'},`
> `responsive: [{breakpoint: 0,settings: {slidesToShow: 2,slidesToScroll: 2}},{breakpoint: 768,settings: {slidesToShow: 3,slidesToScroll: 3}}]`
> `}) });`
> `});`
> `</script>`
> 
> Best wishes,
> Alex

Hey Alex, you solve this? If so, how.

**Comment by ralex78** [comment]
Hi dsacramone,

Unfortunately I could not find a way to solve this. I am now using Owl Carousel 2 on desktop devices and went for a simple CSS only solution (native browser scrolling) on mobile devices.

Best,
Alex

**Comment by NickPiscitelli** [comment]
Multiple instances with Glider.js is indeed possible, they just need to be initialized properly.

Here are some other issues discussing the topic and providing solutions:

https://github.com/NickPiscitelli/Glider.js/issues/24
