### ISSUE TITLE
Drag causes onClick event to trigger

### ISSUE THREAD

**Issue by chvidev** [NickPiscitelli/Glider.js#183]
Hi,

Very happy with this plugin, however I am facing 1 issue.

We load the HTML dynamically into the slider, each item in de slider has a followup page which we will navigate to on click.

Right now, most of the times when we drag the slider using our mouse, the click event triggers aswel.

Is there a way to prevent this? The stopPropagation() and preventDefault() methods used in the glider.js file itself don't seem to be enough..

**Comment by razvantudorache** [comment]
Hi @chvidev 

I am facing the same problem when I'm using this plugin into an angular project. Do you managed to solve this problem? What was your approach? Thank you!
