### ISSUE TITLE
No auto scrolling for slides.

### ISSUE THREAD

**Issue by BhargavaCreates** [NickPiscitelli/Glider.js#187]
I want my slide to change to the next slide after 2 seconds. I am unable figure a way out for this @NickPiscitelli. Is there any nextSlide function that i can trigger in a setInterval function?

**Comment by dmitriyakkerman** [comment]
> I want my slide to change to the next slide after 2 seconds. I am unable figure a way out for this @NickPiscitelli. Is there any nextSlide function that i can trigger in a setInterval function?

Try to to like this:

`
//Your Glider instance

      let glider = new Glider(document.querySelector('.carousel'), {
        //your Glider options
      });
      
      autoplay(slider, miliseconds) {
            const slidesCount = slider.track.childElementCount;
            let slideTimeout = null;
            let nextIndex = 1;

            function slide () {
                slideTimeout = setTimeout(
                    function () {
                        if (nextIndex >= slidesCount ) {
                            nextIndex = 0;
                        }
                        slider.scrollItem(nextIndex++);
                    }, miliseconds);
            }

            slider.ele.addEventListener('glider-animated', function() {
                window.clearInterval(slideTimeout);
                slide();
            });

            slide();
        }
        
        autoplay(glider, 2000);
`

Let me know if this works. I'm also going to create a little extension for Glider for my needs, which will contain autoplay, infinite scroll and current slide of slides length functions. So hope it's gonna be helpful in a future.

**Comment by BhargavaCreates** [comment]
It's working seamlessly. Thanks a lot, mate. You genuinely saved my day. I was gonna scrap this Glider.js and make my own. @dmitriyakkerman

**Comment by mlipovaca** [comment]
> > I want my slide to change to the next slide after 2 seconds. I am unable figure a way out for this @NickPiscitelli. Is there any nextSlide function that i can trigger in a setInterval function?
> 
> Try to do like this:
> 
> ```
>   let glider = new Glider(document.querySelector('.carousel'), {
>     //Your Glider options
>   });
>   
>   autoplay(slider, miliseconds) {
>         const slidesCount = slider.track.childElementCount;
>         let slideTimeout = null;
>         let nextIndex = 1;
> 
>         function slide () {
>             slideTimeout = setTimeout(
>                 function () {
>                     if (nextIndex >= slidesCount ) {
>                         nextIndex = 0;
>                     }
>                     slider.scrollItem(nextIndex++);
>                 }, miliseconds);
>         }
> 
>         slider.ele.addEventListener('glider-animated', function() {
>             window.clearInterval(slideTimeout);
>             slide();
>         });
> 
>         slide();
>     }
>     
>     autoplay(glider, 2000);
> ```
> 
> Let me know if this works. I'm also going to create a little extension for Glider for my needs, which will contain autoplay, infinite scroll and current slide of slides length functions. So hope it's gonna be helpful in a future.

Hi, do you have a piece of code for having infinite scroll for Glider js ?
