### ISSUE TITLE
Feature Request: Autoplay & Infinite-Mode

### ISSUE THREAD

**Issue by dmitrybret** [NickPiscitelli/Glider.js#20]
Hi Nick! Your slider is super. But i need Autoplay & Infinite-Mode.
Thanks.

**Comment by AndrewBogdanovTSS** [comment]
But I guess it can be easily implemented externally, right? Just a set interval with a call to glider.next() ?

**Comment by NickPiscitelli** [comment]
Infinite mode will not be possible, but there are auto play snippets you
can find by search the issue queue for enhancements.
