### ISSUE TITLE
Make it work with mousewheel scroll ?

### ISSUE THREAD

**Issue by asmirbelkic** [NickPiscitelli/Glider.js#203]
Hi guys is it possible to make Gliderjs works with the mousewheel scroll ?

**Comment by NickPiscitelli** [comment]
It should work by default. If you are intending to translate vertical scrolling into horizontal, you would need to write a custom function to capture and invert the scroll.

**Comment by asmirbelkic** [comment]
noh it's vertical but absolutely nothing happens when i scroll with the mousewheel :/

**Comment by asmirbelkic** [comment]
> It should work by default. 

Btw what do you mean by that ? If there is 6 items and 3 to show and if u mousewheel is it suposed to work ?

**Comment by NickPiscitelli** [comment]
It's a horizontal list. In order for it to work, you must scroll the
mousewheel horizontally. If your scroll mechanism does not natively support
horizontal scrolling, then it will not work.
