### ISSUE TITLE
Loading page with id causes weird bug

### ISSUE THREAD

**Issue by tomasts248** [NickPiscitelli/Glider.js#207]
You can check it out here
https://www.franciscagonzalezriedel.com/acerca-de-fg/#timeline
Do note I did try the newest version and causes the same error in the console:
![image](https://user-images.githubusercontent.com/32283036/136889125-96a6d3d7-80ea-46ab-b3da-e4d78f2de146.png)

**Comment by tomasts248** [comment]
In case I wasn't clear. links with anchors don't work if there's a glider.js slider on that page

**Comment by tomasts248** [comment]
I'm definitely avoiding this plugin in the future sadly, no support for bugs even when fixing it it takes ages, I'm done with it

**Comment by NickPiscitelli** [comment]
Can you please provide a working reproduction of this error? There are no known issues with links.

**Comment by tomasts248** [comment]
Okey, clicking here: does not jump to the id section of the page on Google Chrome (it does in Firefox)
working link: https://www.franciscagonzalezriedel.com/acerca-de-fg/#timeline
which should load this: 
![image](https://user-images.githubusercontent.com/32283036/147509997-f2beb68c-e94b-4608-a6e4-1ef2b7899b7b.png)
Do note this is a mix of an anchor link with a page link, I tried locally removing the slider section and it worked in Google Chrome.

**Comment by NickPiscitelli** [comment]
This must be an issue with something on the website, anchor links work fin with Glider as showcased in the documentation.

https://nickpiscitelli.github.io/Glider.js/#methods

**Comment by tomasts248** [comment]
"must be" so can't you check on your end? I did and removing the slider fixed it, as stated earlier is a mix of a link with an anchor link that does not work, I'm not referring to anchor links alone.

**Comment by NickPiscitelli** [comment]
Can you please be specific in your reports then? Anchor links have nothing to do with Glider. I did check your website and this is an implementation issue, not a plugin issue.

If there is a specific issue with Glider, please create a playground that showcases the issue with the exact steps to reproduce.

Github Issues are not free tech support.

**Comment by tomasts248** [comment]
And what about the console JS log error then? that i posted in the first description?

**Comment by NickPiscitelli** [comment]
What about the playground I asked for in the last comment? It's ridiculous to think I would read through your custom application logic.

**Comment by tomasts248** [comment]
That's what I thought I provided in the first post, anyways here it is again: https://www.franciscagonzalezriedel.com/ go there and click this link you will notice it won't load the anchor and the link.
![image](https://user-images.githubusercontent.com/32283036/147512485-e62476ff-2c60-4cb8-b68c-04278e458daa.png)

**Comment by NickPiscitelli** [comment]
That's not a playground, that is your custom website. It has a lot of application logic surrounding it that can be affecting the plugin. When submitting issues to open source, the issues should be contained and demoed in a siloed environment, such as https://jsfiddle.net/

On your website, the error is thrown regardless of the anchor which makes your initial post contradictory. I'm honestly happy to try and help you with your issue, but it needs to be properly reported and you can be more grateful in the process. Three months for single developer's hobby project, during a holiday season no less, is not something I would consider inactive anyway, especially considering the severity level of the bugs reported.

If you are looking for more, then please look elsewhere.

**Comment by tomasts248** [comment]
> I'm honestly happy to try and help you with your issue, but it needs to be properly reported and you could try and be more thankful in the process

Alright noted and I can of course make a Codepen.

If you are looking for more, then please look elsewhere.

I did before I will of course do so in the future

**Comment by tomasts248** [comment]
I'm afraid no playground I'm aware of can recreate a link to another page, if you do now of one post it, anyways I'm staying away from your slider in the future so fear not. attitude * (knowledge + skill) even if your slider is the best your attitude towards the user is no good.
quoting yourself:

> Correct, they do not owe their users anything. Their users should be grateful that such wonderful products are released for free. If they owe anyone anything, it's their donors; certainly not their users.
