### ISSUE TITLE
Not dragged on mobile

### ISSUE THREAD

**Issue by wireinet** [NickPiscitelli/Glider.js#218]
Hello! I find your library is very useful! 
but i upset :(
On mobile i can't drag track to the next slide by my fingers
And i cant find appropriate settings!
This is possible?

**Comment by NickPiscitelli** [comment]
I'm not sure I understand the question. The library uses native scrolling,
you can simply scroll the glider with your finger.

Refer to the documentation site for examples.

**Comment by wireinet** [comment]
Hm...maybe I do something wrong?
Anyway. Thanks! I'll go back if I'll can't find the solution

**Comment by wireinet** [comment]
Demos works fine! Sorry, maybe something wrong with my classes
