### ISSUE TITLE
Add inertia support to scrollLock

### ISSUE THREAD

**Issue by jasongerbes** [NickPiscitelli/Glider.js#22]
Currently, `scrollLock` will lock after inertial scrolling has completed. This causes a rough transition.

Would it be possible to improve support for inertial scrolling when using `scrollLock`?

**Comment by NickPiscitelli** [comment]
Unfortunately not, that is incredibly cumbersome to do and is significantly exacerbated by native scrolling. Any functionality of this sort would requiring adding velocity plugins as a dependency and is not being considered at this time.
