### ISSUE TITLE
Google Core Web Vitals Diagnostic error

### ISSUE THREAD

**Issue by ifrountas** [NickPiscitelli/Glider.js#247]
Hi there is a diagnostic error in core web vitals score.

Does not use passive listeners to improve scrolling performance  and the hint is 

Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. [Learn more](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=lr).

**Comment by anuj9196** [comment]
Hi, @ifrountas @kevinfarrugia Is there any update on this issue? I'm also getting the same warning in Google Lighthouse.

**Comment by NickPiscitelli** [comment]
It's easy enough to update the library to use passive listeners.

Let me research this more and I'll add if there is no drawback.

**Comment by sms20** [comment]
Hi, this is also getting flagged for us in PageSpeed Insights (https://pagespeed.web.dev/).

I noticed this working branch: https://github.com/NickPiscitelli/Glider.js/tree/passive-listeners.. In my limited testing this branch does seem to fix the issue.

Please can you provide an update.

Thanks.

**Comment by oconnorjoseph** [comment]
Hello @NickPiscitelli, also getting this flagged. That same branch looks to work for us as well. Any development would be heavily appreciated.

**Comment by NickPiscitelli** [comment]
This is now available as an option in 1.7.9 called `passiveListeners`; let
me know if this works for you.

I will look into making this the default but I have hesitations around
suppressing the scrolling for horizontal wheels and need to look further
into it.
