### ISSUE TITLE
How to display two slider on single page

### ISSUE THREAD

**Issue by Sushil333** [NickPiscitelli/Glider.js#26]
Hey guy's i am trying to implement two gliders on a index page the first glider is working properly but not the second one please help...

**Comment by NickPiscitelli** [comment]
You are probably experiencing a problem with your selectors similar to this previous issue:

https://github.com/NickPiscitelli/Glider.js/issues/24

Please review the contents of that issue and adjust your selectors as demonstrated. If you are still experiencing issues, please provide your initialization code and appropriate markup.

**Comment by Sushil333** [comment]
@NickPiscitelli 
        Thank you.
