### ISSUE TITLE
`draggable: false` not working in mobile

### ISSUE THREAD

**Issue by blaadje** [NickPiscitelli/Glider.js#267]
Hi, 
unless im missing something setting the `draggable` option to `false` still allows the drag in **mobile** (working fine in desktop).

_PS: this test is with chrome mobile emulator but the result is the same with a real mobile._

https://github.com/user-attachments/assets/b18cb882-26d1-42c9-b6b0-b102f39e51e7

**Comment by blaadje** [comment]
I switched to glidejs

**Comment by NickPiscitelli** [comment]
`draggable` is a desktop only option.

On mobile it's just called scrolling
