### ISSUE TITLE
Responsive settings ignored after setOption()

### ISSUE THREAD

**Issue by jasongerbes** [NickPiscitelli/Glider.js#27]
When using responsive settings, the updated responsive settings are ignored after calling `setOption()`, until the window is resized and the breakpoint changes.

**Reproduction steps:**

1. Create a glider instance with responsive settings, for example:
```
const options =  {
    slidesToShow: 2,
    responsive: [
        {
            breakpoint: 500,
            settings: {
                slidesToShow: 4
            }
        }
    ]
};

const glider = new Glider(element, options);
```
2. Resize your window to >=500px so that the responsive settings are being enforced (4 slides).
3. Call `setOption()` and then `refresh()`.
```
glider.setOption(options, true);
glider.refresh();
```
4. Observe how the responsive settings are not being enforced (2 slides instead of 4).
5. Resize your window (make it <500px and then >=500px).
6. Observe how the responsive settings are now being enforced (4 slides).

**Comment by NickPiscitelli** [comment]
This should be fixed in the latest version. Thanks for reporting the error (and for the detailed steps on reproducing).

Let me know if you are still experiencing issues after updating the library.

**Comment by jasongerbes** [comment]
Thanks for the quick response and fix! It seems to be working perfectly now
