### ISSUE TITLE
Add option to prevent DOM restructuring

### ISSUE THREAD

**Issue by jasongerbes** [NickPiscitelli/Glider.js#28]
Glider will currently restructure the DOM on initialisation, moving the children of `_.ele` into a new `<div class="glider-track"`.

This poses an issue when using Glider in React, as such a DOM manipulation is not tracked. Specifically, when re-rendering changes to the children of the Glider, React will attempt to remove the existing children -- which it expects to be direct descendants of `_.ele`, but as they have now moved, React crashes.

Having tried out a few options, I believe that the best solution would be to add an option (e.g. `addTrack`, default = `true`) that can prevent Glider from restructuring the DOM. That way, the new behaviour would be opt-in and non-breaking to existing users of Glider.

To use Glider with the new option, this:

```html
<div class="glider-contain">
  <div class="glider">
    <div>your content here</div>
    <div>your content here</div>
    <div>your content here</div>
    <div>your content here</div>
  </div>

  <button role="button" aria-label="Previous" class="glider-prev">«</button>
  <button role="button" aria-label="Next" class="glider-next">»</button>
  <div role="tablist" class="dots"></div>
</div>
```

... would become this:

```html
<div class="glider-contain">
  <div class="glider">
    <div class="glider-track"> <!-- this div would need to be added manually by the integrator -->
      <div>your content here</div>
      <div>your content here</div>
      <div>your content here</div>
      <div>your content here</div>
    </div>
  </div>

  <button role="button" aria-label="Previous" class="glider-prev">«</button>
  <button role="button" aria-label="Next" class="glider-next">»</button>
  <div role="tablist" class="dots"></div>
</div>
```

In glider.js, something like the following code could be used to support this new option:

```js
if (_.opt.addTrack) {
    _.track = document.createElement('div')
    _.track.className = 'glider-track'
    _.ele.appendChild(_.track)
    while (_.ele.children.length !== 1) {
        _.track.appendChild(_.ele.children[0])
    }
}
else {
    _.track = _ele.children[0]
}
```

Please let me know your thoughts. If you'd like, I could create and submit a PR for the proposed changes

**Comment by NickPiscitelli** [comment]
Do you know if the problem exists in the React version of the Glider?

https://www.npmjs.com/package/react-glider

**Comment by jasongerbes** [comment]
Yes it does, I opened an issue: https://github.com/hipstersmoothie/react-glider/issues/1

**Comment by NickPiscitelli** [comment]
What's the solution for this problem? I'm welcome to accept a pull request
if it doesn't add much bloat and has no side effects for individuals not
using React.

**Comment by NickPiscitelli** [comment]
Oh, never mind. I didn't read the whole post at first. I'll look into it.

**Comment by jasongerbes** [comment]
Would you like to me submit a PR? Happy to work on it now if so

**Comment by NickPiscitelli** [comment]
Sure, send it over. Just make sure to run a `yarn install` on the
repository before submitting a pull request since it runs all the linters
and minfiers. All you need to do is modify glider.js in the project root
and the rest will take care of itself with a commit hook.

You're welcome to update the documentation as well, but don't feel
obligated to. I'll update them after accepting the pull request if you
don't.

Thanks for looking into all of this and reporting these issues, really
appreciate it!

**Comment by jasongerbes** [comment]
@NickPiscitelli Could you please release a new version when you have closed this?

**Comment by NickPiscitelli** [comment]
Do you mean to npm? If so, it was just submitted :)
