### ISSUE TITLE
Consider adding user-select: none to arrows

### ISSUE THREAD

**Issue by arggh** [NickPiscitelli/Glider.js#3]
Just took a look out of curiosity and noticed some glitches in the demos.

It's really easy to get the dot elements representing the scroll location selected when trying to click the slideshow arrows. Image explains better:

<img width="1185" alt="glider" src="https://user-images.githubusercontent.com/17210302/48317155-c6832880-e5f6-11e8-8117-054e91a22845.png">

This would probably be remedied by adding `user-select: none;` to those arrows.

**Comment by NickPiscitelli** [comment]
Good catch, will add with next release, likely some time tonight.

**Comment by NickPiscitelli** [comment]
This has been added
