### ISSUE TITLE
iOS Safari 10 dont support classList.forEach

### ISSUE THREAD

**Issue by alexesDev** [NickPiscitelli/Glider.js#31]
Hotfix:
```js
// copy from https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
if (!DOMTokenList.prototype.forEach) {
  DOMTokenList.prototype.forEach = function(f) {
    if (arguments.length === 1) for (var i = 0, Len = this.length; i !== Len; ++i) f(this[i], i, this);
    else for (var i = 0, Len = this.length, tArg = arguments[1]; i !== Len; ++i) f.call(tArg, this[i], i, this);
  };
}
```

**Comment by NickPiscitelli** [comment]
Are any devices still running Safari 10?

Do you happen to know if `[].forEach.call(element.classList, function(){})` works?

**Comment by alexesDev** [comment]
> Are any devices still running Safari 10?

We release a new version of our mobile site and get many errors from customers (~5%).

> Do you happen to know if [].forEach.call(element.classList, function(){}) works?

Works

**Comment by alexesDev** [comment]
Also ie11 (win phone) dont support window.CustomEvent

**Comment by NickPiscitelli** [comment]
I'll update it to use `[].forEach.call` later this evening and deploy a new
release. I tried to always use `[].forEach.call` to avoid issues like this,
but it seems I must have missed a few.

**Comment by NickPiscitelli** [comment]
IE11 is not supported, but there is a `glider-compat.min.js` that includes
all the necessary polyfills, including CustomEvent.

**Comment by alexesDev** [comment]
@NickPiscitelli thanks!

**Comment by NickPiscitelli** [comment]
Updated. Sorry, completely forgot to release. Looking into automating this
process entirely.
