### ISSUE TITLE
Cannot re-init slider. 

### ISSUE THREAD

**Issue by pxwee5** [NickPiscitelli/Glider.js#36]
After destroying slider there's no way to re-initialize it.

**Comment by pxwee5** [comment]
I know why, because it is a virtual dom of a vue component. Glider doesn't play nice with them yet.

**Comment by NickPiscitelli** [comment]
I'm sure we can, but I don't know too much about them. Any idea what it entails to provide support for this? It doesn't delete the elements so I would think it should happily re-initialize, but I never worked with virtual DOMs before.

**Comment by NickPiscitelli** [comment]
Closing this issue due to lack of response
