### ISSUE TITLE
Surpassing slides

### ISSUE THREAD

**Issue by grafmichel** [NickPiscitelli/Glider.js#39]
Hi Nick
Thanks for this small, fast library. - I have a gallery with 12 pictures in total, only 3 pictures are visible at a time. Hitting 'next' button works for pics no. 4-6. Than, hitting again, it surpasses pics 7-9 und goes directly to pics 10-12. Hitting than the 'back' button works as expected (showing 7-9, than 4-6 and 1-3). Anything I can do? Same behavior for differents pictures. - Thanks, Oliver

**Comment by NickPiscitelli** [comment]
Hi Oliver,

Would you be able to provide a codepen, JS fiddle, or link to your website
so that I can recreate the behavior? It sounds like the buttons may have
been bound twice, but it's tough to say without actually seeing it in
action.

**Comment by grafmichel** [comment]
Thanks for the fast reply, I appreciate very much. Link is [here](https://www.raumanzug.eu/bim/koordination.html).

**Comment by NickPiscitelli** [comment]
Sorry for the late reply, I was on vacation and had just gotten back.
Anyway, I think your issue might be due to the fact you are passing strings
for `slidesToScroll` and `slidesToShow` arguments. Can you try and pass
bare numbers and see if that fixes the problem?

**Comment by grafmichel** [comment]
oh happy day! that was it! Great happiness here - thank you so much!

**Comment by NickPiscitelli** [comment]
No problem, happy to help!
