### ISSUE TITLE
Add and enable TravisCI

### ISSUE THREAD

**Issue by DanielRuf** [NickPiscitelli/Glider.js#4]
We should have Travis CI running for every commit and PR and provide some unit tests.

**Comment by NickPiscitelli** [comment]
I've definitely been wanting to add a testing framework, this is my first
project on Github where it's actually been warranted. I'll look into Travis
CI, thanks for the heads up.

**Comment by DanielRuf** [comment]
Let me know if you need any help with the decision for the "right" testing framework and other things (creating and publishing as a npmjs package).

**Comment by NickPiscitelli** [comment]
I was thinking of using Jest, what are your thoughts? What would you
recommend?

**Comment by DanielRuf** [comment]
I would have also recommended Jest.

**Comment by DanielRuf** [comment]
Why was this closed without any further info?

**Comment by NickPiscitelli** [comment]
Mistake, I thought enhancements were a separate queue as opposed to issues, but it looks like it just needs to be appropriately tagged.
