### ISSUE TITLE
Last slide not always "visible" when at end of track.

### ISSUE THREAD

**Issue by l3v1k** [NickPiscitelli/Glider.js#40]
Hi and thank you for this library!

I have added some custom style animations to my slides and noted that last slide not triggering className 'visible' when track scrolled to the end. Also this bug present in [Glider demos](https://nickpiscitelli.github.io/Glider.js/#demos).

You can see it here:

<img width="1041" alt="screen shot 2019-02-26 at 11 51 34" src="https://user-images.githubusercontent.com/6277287/53404004-6a81bb80-39bd-11e9-8155-88e7a238bf46.png">

As you can see "navigation" right arrow is disabled, that means scroll in the end of track.

**Comment by NickPiscitelli** [comment]
How did you re-create the scenario? Normally this scenario happens when there is a small gap of a few pixels before the actual end of the content. When I use the arrows/dots myself on navigation, it does properly add the visible class as expected.

**Comment by l3v1k** [comment]
I used only examples on project site. You can check it yourself eg. in example **Multiple Item**. 

<img width="1011" alt="Screen Shot 2019-04-05 at 12 17 26" src="https://user-images.githubusercontent.com/6277287/55617581-18db0680-579d-11e9-9d07-20ee84274922.png">

Scroll this list to the end and inspect last element. It doesn not have "visible" in the classList. :(

**Comment by NickPiscitelli** [comment]
What method are you using to scroll the glider? Touch based scrolling, mouse wheel, etc?

**Comment by l3v1k** [comment]
I tried all of methods: swipe (scroll wheel), drag, pressing next arrow. Same behaviour with no visible at last item. Also i checked this in Chrome, Firefox Quantum and Safari. **Multiple Item** and **Perspective View** have same buggy behaviour in all browsers, other examples works as expected.

Don't you have same behaviour?

![ezgif-2-8c67a88a9d08](https://user-images.githubusercontent.com/6277287/55701350-7a88b400-59db-11e9-9b6a-87799403310f.gif)

**Comment by NickPiscitelli** [comment]
![Selection_028](https://user-images.githubusercontent.com/1686933/55797374-390b0e00-5a9a-11e9-8924-052b0e557597.png)


Not when using the paging elements, dragging or emulated scrolling; that's why I asked for your input method.

I did not test native scrolling though as it would be a bit more cumbersome to test and was only going to if that was actually the method in question.

Anyway, after some brute force testing, I was able to re-create this myself in a codepen ; I'll take a look and see what the the issue is when I have a minute. This is common with scrolling due to edge resistance, but it's odd that it's happening with paging controls as well.

**Comment by NickPiscitelli** [comment]
Can you confirm if the latest version fixes this issue?

**Comment by tyom** [comment]
I've also come across this problem. It appears that there's a rounding pixel issue for the item end calculation. If I resize the viewport just a bit it hits the right value.

![js-glider-last-slide-rounding-issue](https://user-images.githubusercontent.com/203886/58472185-9d168e00-813d-11e9-945b-0bcdde834478.gif)

**Comment by tyom** [comment]
Should it `floor` instead of `ceil`?
```js
var isVisible =
         Math.ceil(itemStart) >= start && Math.floor(itemEnd) <= end
```
