### ISSUE TITLE
multiple sliders

### ISSUE THREAD

**Issue by giveitweb** [NickPiscitelli/Glider.js#41]

**Comment by NickPiscitelli** [comment]
Multiple sliders are able to be initialized as one would expect, what is the issue you are having?

**Comment by CyrilAntoni** [comment]
Hi there,

I had an issue with using multiple Gliders on the same page as well.
So I did a sandbox and got it working!
All I did was to give different id names to each arrow pairs. I also use an id to initiate the slider to clarify what is used for design and what is used for targeting the slider.

Here is a minimal working example:
https://codesandbox.io/s/multiple-glider-sliders-lufwo?fontsize=14

Maybe we should update the documentation to include a multi-slider example?

**Comment by michaelguild13** [comment]
`const carousels = document.querySelectorAll('.glider');
    Object.values(carousels).map(carousel => {
      new Glider(carousel, {
        slidesToShow: 4,
        slidesToScroll: 4,
        scrollLock: true,
        arrows: {
          prev: carousel.parentElement.getElementsByClassName('carousel-previous-button')[0],
          next: carousel.parentElement.getElementsByClassName('carousel-next-button')[0]
        }
      })
    });`

**Comment by architchandra** [comment]
Yes, please add an example of using multiple sliders on the same page in the docs.

**Comment by RilDev** [comment]
Here you go @architchandra!

While waiting for the PR to be reviewed, you can check this Glider example: https://codesandbox.io/s/multiple-glider-sliders-lufwo?fontsize=14

If you need help to understand how it works, just ask!

**Comment by architchandra** [comment]
@RilDev - I guess I should have mentioned that explicitly, but adding multiple slides programmatically was more on the lines of what I was requesting for.

Something like the following (but better and more DRY):
```
var carouselList = document.querySelectorAll('.carousel');

for(var i = 0; i < carouselList.length; i++) {
  new Glider(carouselList[i], {
    draggable: true,
    arrows: {
      prev: carouselList[i].parentElement.parentElement.querySelectorAll('.arrow-prev')[0],
      next: carouselList[i].parentElement.parentElement.querySelectorAll('.arrow-next')[0],
    },
    dots: carouselList[i].parentElement.parentElement.querySelectorAll('.dots')[0],
    rewind: true,
  });
}
```

**Comment by RilDev** [comment]
You could try something like it then:

```
const gliders = document.querySelectorAll("[id^=glide]");

for (let i = 0; i < gliders.length; i++) {
  const counter = i + 1;

  new Glider(document.querySelector(`#glider-${counter}`), {
    slidesToShow: 3,
    draggable: true,
    dots: `.dots-${counter}`,
    arrows: {
      prev: `.glider-prev-${counter}`,
      next: `.glider-next-${counter}`
    }
  });
}
```

Here is a working example: https://codesandbox.io/s/gifted-germain-ndzcp?file=/src/index.js:1297-1662

**Comment by RilDev** [comment]
@architchandra, is this closer to what you were looking for? https://codesandbox.io/s/glider-procedural-multiple-init-ndzcp

I also improved the code in the previous message to make it _Sahara_ DRY!

**Comment by architchandra** [comment]
@RilDev - Yes, thank you! I also did something similar only.

**Comment by tomasts248** [comment]
Question why something like this doesn't work?
`<script` defer type="text/javascript">

 window.addEventListener('load', function(){
              new Glider(document.getElementById('glider-testimonios'), {
            slidesToShow: 1, //'auto',
            slidesToScroll: 1,
            itemWidth: 'auto',
            draggable: true,
            scrollLock: false,            
            dots: '#dots-testimonios',
            rewind: true,
            arrows: {
                prev: '#glider-prev-testimonios',
                next: '#glider-next-testimonios'
            },
            responsive: [

    {
      // screens greater than >= 775px
      breakpoint: 483,
      settings: {
        // Set to `auto` and provide item width to adjust to viewport
        slidesToShow: 1,
        rewind: true,
        slidesToScroll: 1,
        itemWidth: 482,        
        duration: 0.25,
        exactWidth: true
      }
      },
    {
      // screens greater than >= 775px
      breakpoint: 974,
      settings: {
        // Set to `auto` and provide item width to adjust to viewport
        slidesToShow: 2,
        rewind: true,
        slidesToScroll: 2,
        itemWidth: 482,        
        duration: 0.25,
        exactWidth: true
      }
      },{
      // screens greater than >= 1024px
      breakpoint: 1488,
      settings: {
        slidesToShow: 3,
        rewind: true,
        slidesToScroll: 3,
        itemWidth: 482,
        duration: 0.25,
        exactWidth: true
        

    }
    }
  ]
        });
      });

/* segunda instancia para slider medios */

 window.addEventListener('load', function(){
              new Glider(document.getElementById('glider-single'), {
            slidesToShow: 'auto', //'auto',
            slidesToScroll: 'auto',
            exactWidth: false,
            itemWidth: 220,
            draggable: true,
            scrollLock: false,
            dots: '#dots-medios',
            rewind: true,
            resizeLock: false,
            arrows: {
                prev: '#glider-prev-medios',
                next: '#glider-next-medios'
            },
            responsive: [
                {
                    breakpoint: 530,
                    settings: {
                        slidesToScroll: 'auto',
                        itemWidth: 180,
                        slidesToShow: 'auto',
                        exactWidth: false,
                        resizeLock: false
                    }
                },
                {
                    breakpoint: 800,
                    settings: {
                        slidesToScroll: 'auto',
                        itemWidth: 280,
                        slidesToShow: 'auto',
                        exactWidth: false,
                        resizeLock: false
                    }
                }              
                
            ]
        });
      });

</script>
