### ISSUE TITLE
Cannot assign to read only property 'window' of object '#<Window>'

### ISSUE THREAD

**Issue by StarpTech** [NickPiscitelli/Glider.js#42]
I get the error in the browser:
```
Uncaught TypeError: Cannot assign to read only property 'window' of object '#<Window>'
```
Search for `window="undefined"` [here](https://github.com/NickPiscitelli/Glider.js/blob/master/glider.min.js)

**Comment by NickPiscitelli** [comment]
Can you provide a fiddle that re-creates the error? How are you loading the module?

**Comment by StarpTech** [comment]
I could solve it by disabling babel for that specific file. I think the reason why you couldn't reproduce it is that my file runs in `use strict;` mode.

**Comment by StarpTech** [comment]
You can reproduce it if you set `use strict;` at the beginning of the `slider.js`

**Comment by NickPiscitelli** [comment]
Right, that makes sense as it's exposed via the `window` object. It would
probably be best to abstract that out, there really isn't much reason for
it aside from convenience, but there's always alternatives.

**Comment by StarpTech** [comment]
This is not a feature. In strict mode the slider doesn't work.

**Comment by NickPiscitelli** [comment]
Strict mode is considered best practice, but the inability to operate
inside of it is not a bug, therefore it is on the road map as an
enhancement.

**Comment by NickPiscitelli** [comment]
Strict is already enabled on the plug-in, I'm confused on how exactly you are triggering this error?

**Comment by NickPiscitelli** [comment]
Never mind, I see what is causing the error.

**Comment by StarpTech** [comment]
Thanks!
