### ISSUE TITLE
Browser support for scrollbar styling

### ISSUE THREAD

**Issue by abdusco** [NickPiscitelli/Glider.js#45]
A majority of browsers support `scrollbar-width` property, including recent versions of Firefox, which means there's no need for the hacks detailed in the documentation.

- https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
- https://www.caniuse.com/#feat=css-scrollbar

**Comment by NickPiscitelli** [comment]
Awesome. I will update the readme. That is quite useful.
