### ISSUE TITLE
Glider can be "stuck", unable to complete slide transition and triggering multiple "glider-animated" events

### ISSUE THREAD

**Issue by filip-savic** [NickPiscitelli/Glider.js#48]
Glider can become "stuck" while trying to complete transition. Maybe there is some kind of mismatch in the math related to the track / items. 

The problem is you can't rely on the `glider-animated` event as it's triggered multiple times, for as long as Glider is "stuck".

The use case where I had this problem is using the `glider-animated` event as a trigger for reseting a timer for an autoplay function.

-----

Reproduce bug on this codepen (tried on Chrome while dev tools ):

https://codepen.io/fsavic/pen/EByGrd

1. Drag the glider around until it's in the "stuck" state
2. The output will display multiple "animation complete event" texts, triggered by the `glider-animated` event
3. Inspect the elements, and you'll see they are changed non-stop

**Comment by NickPiscitelli** [comment]
Interesting, thanks for the detailed explanation and recreation. I'll take
a look this evening and try to resolve this issue.

**Comment by NickPiscitelli** [comment]
Can you let me know if the latest release fixes your issue?

**Comment by filip-savic** [comment]
@NickPiscitelli It does - tested both on codepen and on my local implementation. Very quick fix :clap: 

However, now the `scrollLock` functionality seems to be broken now. When dragging the track, the slides don't snap - https://codepen.io/fsavic/pen/NZRJZV (codepen with release 1.6.7)

**Comment by NickPiscitelli** [comment]
I suppose this is why I need unit tests...

I'll take another look this evening and try to fix it - without breaking
anything else along with it :)

**Comment by NickPiscitelli** [comment]
Sorry for the long delay, but hopefully the latest release resolves this with no regressions.

**Comment by filip-savic** [comment]
@NickPiscitelli Thanks, everything is working as expected! :)
