### ISSUE TITLE
Duplicate In Documentation: scrollPropagate

### ISSUE THREAD

**Issue by CyrilAntoni** [NickPiscitelli/Glider.js#54]
Hi,

The scrollPropagate entry in the documentation seems to be duplicated.

![image](https://user-images.githubusercontent.com/13135150/64434966-02c1d100-d0c2-11e9-8f0f-322591a6f410.png)

Thank you for the great ~~slider~~ uh, glider!

**Comment by NickPiscitelli** [comment]
What's the matter, you don't like redundancy?

Just kidding, nice catch. I've updated the docs.
