### ISSUE TITLE
.center is a terrible, terrible classname and you should feel bad (please don't though)

### ISSUE THREAD

**Issue by SephReed** [NickPiscitelli/Glider.js#59]
Lovely tool, quite like it.  I'm having conflicts with the fact that I already have a css class called `center` which I use for (can you guess it)... centering text.  

It's pretty easy for me to override this singular property, but I still felt important to point out: this is a terrible, terrible classname for a utility to assume ownership of.

It's probably too late to change it, but (if it's possible), you should really consider changing your css names to be less likely to conflict.  `active` and `draggable` were a few others that seemed really capable of causing trouble.

**Comment by NickPiscitelli** [comment]
Fair enough; they definitely should have been prefixed with the plugin
name. I'd be happy to accept a pull request to rectify the issue :)

**Comment by SephReed** [comment]
Thank you for letting me know you're open to the consideration.  I get the feeling it might break some backwards compatibility so I'm a bit nervous about that. 

The workflow is just these two files, right?
- https://github.com/NickPiscitelli/Glider.js/blob/master/glider.css
- (https://github.com/NickPiscitelli/Glider.js/blob/master/glider.js  

And from there I imagine you have a tool for minifying and creating the compaq version... or would I need to do that too?

**Comment by NickPiscitelli** [comment]
Yeah, just those two files. If you clone the repo, then run `npm install`,
it will run all the linters and build process when you run `git commit`.
All you would need to do is:

   - Clone repo
   - Run `npm install`
   - Make your changes
   - Commit them
   - Send pull request

I wouldn't worry about backwards compatibility, anyone upgrading the plugin
should grab both the new JS and CSS files. As long as it is noted in the
README and the release notes, I don't think it would be much of a problem.

**Comment by SephReed** [comment]
Coolio.  Ty very much.

**Comment by beyer-stefan** [comment]
I cloned the repository and renamed in the file glider.js the class name 'center' in slideClasses.add (line 315) and slideClasses.remove (line 317) to 'glider-center'. 

But: I cannot find a class named 'center' in the .css file at all?! Are you still using that class or is it dead code?! I am confused...

**Comment by SephReed** [comment]
I stopped working for the company this project was for a while ago.  Sorry I can't be of more help.
