### ISSUE TITLE
Glider element should not be centered via margin

### ISSUE THREAD

**Issue by muuvmuuv** [NickPiscitelli/Glider.js#67]
On my page there is no use for this and I want to give the glider a margin bottom which is only possible with `!important` because the glider css overrides my styles which are selected with another css selector called `videos-container`. IMO things like styling, positioning etc are things for themes or the user itself should style not the lib.

It is just one line of code but over all it is nice for a lib to have as little as possible of css and js.

**Comment by NickPiscitelli** [comment]
While I agree with the premise, providing basic standard theme CSS cuts
down on the number of reported issues and contact I get substantially. You
may always just remove those lines from the CSS, or simply provide a basic
override. There is no need for important unless you are loading the library
CSS after you own, in which I suggest you reverse the order (or simply
provide another selector for specificity).
