### ISSUE TITLE
Using transform instead of native overflow scroll?

### ISSUE THREAD

**Issue by muuvmuuv** [NickPiscitelli/Glider.js#68]
Each of my elements have a shadow which gets cutted when using `overflow` method. Would it be possible to change the behavior to use transform? 
So the `glider-track` would also get a `transform: translateX(-280px);`.

**Comment by NickPiscitelli** [comment]
No, it's specific purpose is to use native scrolling, that's the whole
point of the plug-in. If you want transforms, you should look into Glide.js
or Siema.

**Comment by NickPiscitelli** [comment]
With respect to your shadow issue, you can always use child containers and add the shadow to them.
