### ISSUE TITLE
Basic CSS Override

### ISSUE THREAD

**Issue by helderscrolls** [NickPiscitelli/Glider.js#69]
Hey there,

feeling quite dumb but I can't find a logical way to override the dots classes without having to actually modify the glider.css or glider.min.css file ..

Any tips on the correct way to apply basic changes on existing classes for the dots like changing the background color etc ?

**Comment by NickPiscitelli** [comment]
You can just insert a CSS rule in your own CSS file, just make sure you
load it after loading Glider.

.glider-dots { ..styling }
