### ISSUE TITLE
Scrollbar in firefox developer 72.0b2 doesn't hidden

### ISSUE THREAD

**Issue by migsandia** [NickPiscitelli/Glider.js#71]
Hi!

We have problems with last update in firefox developer, scrolling 'x' doesn't hidden.
You know this problem and how fix it?

thanks!

**Comment by NickPiscitelli** [comment]
I'm not sure why you are referring to, can you send a screensbot?

**Comment by migsandia** [comment]
![scroll-x-bar - copia](https://user-images.githubusercontent.com/46279849/70432726-337a2380-1a80-11ea-83ea-aa384b7c1ba6.JPG)

**Comment by GustaveD** [comment]
Hello everyone,
any updates?
thanks

**Comment by NickPiscitelli** [comment]
Hi Gustave

The scrollbars are hidden for me in FF, but there are solutions for dealing with scrollbars in FF in the README.

https://github.com/NickPiscitelli/Glider.js#native-scrollbars

**Comment by zavada123** [comment]
But it doesn't work for chrome browser and xiaomi mobile browser :(

**Comment by NickPiscitelli** [comment]
You should be able to use the webkit scrollbar styling in Chrome. I'm not familiar with the xiaomi browser at all.

**Comment by zavada123** [comment]
Ok, so how can I fix it on Chrome, can you help to me?
http://prntscr.com/qsclj6 - screen from mobile version chrome on notebook.

**Comment by brunopinhal** [comment]
Hi! I was reaching the same problem.

To solve this, I just set the ::-webkit-scroll as display none, into the glider wrapper as the example bellow:

`    .glider ::-webkit-scrollbar  {
        display: none;
      }
`

ps: The glider selector is the class that GliderJs puts into the div that involve your slider items.

I hope it helps you! 😁🤘🏼

**Comment by panfanky** [comment]
In firefox in fiddles like this I googled 
http://jsfiddle.net/m4cjukLr/?utm_source=website&utm_medium=embed&utm_campaign=m4cjukLr

(and on my page with basic setup too), I see the horizontal scrollbar. Setting overflow-x to hidden disables the touch swipe functionality. I don't see it on demos on your page though.

brunopinhal's solution unfortunatelly doesn't seem to do anything.

**Comment by tomasts248** [comment]
Yep that fix is not working here as well

**Comment by tomasts248** [comment]
I managed to hide the scroll bar behind the dots, but this is a hacky solution..
```
.glider-dot {
margin-top: -17px;
z-index: 99;
position: relative;
background-color: white;
}
```

**Comment by yaninataran** [comment]
This code works for me:
```
.glider {
    scrollbar-width: none; // firefox
}
.glider::-webkit-scrollbar {
    display: none; // webkit
}
```

**Comment by kasutajaimin** [comment]
Here you go: 

```css
@-moz-document url-prefix() {
	.glider-wrap {
		position: relative;
		overflow: hidden;
	}
}
```

```javascript
if (/((?!like ).{5}|^.{0,4})Gecko|Goanna/.test(navigator.userAgent)) {	// regex accounts for browsers w/o neg. lookbehind
	$(document).on(
		'glider-loaded glider-refresh',
		function (event) {
			event.target.parentNode.style.height = event.target.clientHeight - 1 + 'px';
		}
	);
}
```

Verified on current Pale Moon, Basilisk, Waterfoxes and Firefox.

Humbly suggest to update the relevant README section, at the very least to not give non-working advice.

**Comment by NickPiscitelli** [comment]
Sorry for the late reply. I've tried this solution and am receiving odd behavior. The current solution does appear to still be working for me though.

![image](https://user-images.githubusercontent.com/1686933/135513616-50612254-9b53-4133-8d57-c443e29f45e5.png)

**Comment by NickPiscitelli** [comment]
This works well. I will update the guide; thank you for the solution.

**Comment by WebSpectrum** [comment]
is this fix inlcuded in current build?
