### ISSUE TITLE
The CSS class 'glider-dots' is added every time that the window resize

### ISSUE THREAD

**Issue by python2and3developer** [NickPiscitelli/Glider.js#76]
In line 189, we have:
```js
_.dots.className += ' glider-dots';
```
That line it's inside the function **buildDots**. Every time that a resize is triggered, the method **init** is called. And inside that **init** method if the break point is changed, then the method **buildDots** is called to make the corresponding adaptations in the dots (for example if there is less dots to show after the window resize).

My proposal is to change that line by this one:
```js
    if (!_.dots.classList.contains('glider-dots'))
        _.dots.className += ' glider-dots';
```

I tested and adding this the problem is solved.

**Comment by NickPiscitelli** [comment]
Good catch. You can submit a PR if you like or I'll push out the change shortly. Thanks.
