### ISSUE TITLE
disabled class sometimes missing on next link

### ISSUE THREAD

**Issue by weberdominik** [NickPiscitelli/Glider.js#79]
Sometimes the "disabled" class on the next button will not be set because the width was not calculated correctly as you can see in my console output:
<img width="118" alt="console" src="https://user-images.githubusercontent.com/12546013/73451939-128bcb80-4369-11ea-9062-b53a2b29790e.png">

Maybe the problem only occurs on large displays (4k). I fixed it by changing this line:
https://github.com/NickPiscitelli/Glider.js/blob/9019f3278a92b2126b1810f9c28af722c8cbc187/glider.js#L247
to Math.ceil (Math.ceil(_.ele.scrollLeft + _.containerWidth) >= Math.floor(_.trackWidth)).

**Comment by NickPiscitelli** [comment]
This has been implemented, thanks for the fix
