### ISSUE TITLE
1.7.2 tag missing from GitHub

### ISSUE THREAD

**Issue by agarzola** [NickPiscitelli/Glider.js#93]
The `1.7.2` tag is [missing from this repository](https://github.com/nickpiscitelli/glider.js/tags). This makes it impossible to use GitHub’s Compare view (i.e. `https://github.com/NickPiscitelli/Glider.js/compare/1.7.1...1.7.2`) to examine the changes published in this newer patch version. Services such as Dependabot typically link to that compare view and also try to list all commits between the version currently in use in a project and the new version being updated (currently it can’t do that because of the missing tag).

Would you mind pushing the tag you created when you published version `1.7.2`? Thanks for maintaining this library!

**Comment by NickPiscitelli** [comment]
No problem, thanks for the heads up. This has been completed now. I always forget to tag and publish when making new commits...
